argo-cd:
  global:
    domain: argocd.melby.casa

    networkPolicy:
      create: true

  configs:
    repositories:
      argocd:
        url: https://github.com/hansjmelby/whpah.git

    dex:
      enabled: false
